### PR TITLE
Fix GlyphNotCached when match is not adjacent to order

### LINKED ISSUE #52: Missing glyphs when using the gpu cache
Hi I've recently developed [gfx_glyph](https://github.com/alexheretic/gfx-glyph) which uses this lovely library. I've noticed sometimes glyphs are be missing from the render, see below example of incorrect/correct render.

missing-glyphs

When using the PR code in #39 this issue does *not* occur. So that, or a similar, change would be great.

Fixed by #39.

### PR DESCRIPTION
**Pull request by alexheretic**
As mentioned in #39 this PR adds a new solution to #52. I've also added two benchmarks which highlight the issue and server to avoid performance regression / encourage improvement in the future.

As in #39 I decided to simply solve the failure to find a glyph in the cache will worst-case full traversal. However, I went for a middle out style which is quite similar to the original *check-adjacent* algorithm. 

My method starts from the same place according to BTreeMap ordering, but keeps searching outwards until it finds a left and/or right match instead of stopping after the first two. It'll search this way until it finds at least one match or exhausts the entire cache. After that it works on the 0/1/2 matches in exactly the same way as current code.

In summary it fixes the bug and performs the same way as the current algorithm in all the cases the current algorithm *actually works*. So while it may still not be the perfect algorithm it seems to definitely be an improvement.

rusttype version | position tolerance | benchmark
--- | --- | ---
0.2.1 master | 1.0 | 3,623,762 ns/iter (+/- 49,103)
0.2.1 master | 0.1 | *failed*
PR39-code | 1.0 | 8,378,997 ns/iter (+/- 176,811)
PR39-code | 0.1 | 123,299,414 ns/iter (+/- 804,216)
this PR | 1.0 | 3,579,136 ns/iter (+/- 54,938)
this PR | 0.1 | 63,443,258 ns/iter (+/- 521,366)

Fixes #52 
This will also address #39, and all current dependency update PRs.

Note: I took the liberty of adding a note about the benchmark to the readme. Feel free to remove if this isn't desired.

### CODE REVIEW

**Comment by jackpot51** [comment]
I am requesting transfer to another maintainer, please read and comment here: https://github.com/dylanede/rusttype/issues/55

**Comment by alexheretic** [comment]
I've made further fixes to eliminate missing glyphs caching errors (I think I've got them all now) in a separate fork I made of the gpu_cache code. I also moved to std collections. 

I can make some effort to add these changes if there's interest. Or maybe another PR. Let me know.

**Comment by jackpot51** [comment]
@alexheretic having read through everything, I think I will close #53 (this) and #39 and wait for a new PR. Is that ok?

**Comment by alexheretic** [comment]
Sure I'll put a new pr together when I get time.

**Comment by jackpot51** [comment]
Thanks @alexheretic !

**Pull request closed without merging**
