### PR TITLE
Delete non-free asset

### PR DESCRIPTION
**Pull request by moyogo**
This asset’s license doesn’t allow redistribution:
> You may not copy or distribute this software.

### CODE REVIEW

**Comment by jackpot51** [comment]
I am requesting transfer to another maintainer, please read and comment here: https://github.com/dylanede/rusttype/issues/55

**Comment by jackpot51** [comment]
Thanks!

**Comment by alexheretic** [comment]
Unfortunately the replacement example font doesn't seem to render the gpu_cache example properly. 
It's missing Japanese glyphs presumably.

**Comment by jackpot51** [comment]
That's ok. I will look into adding free as in freedom example fonts to a second repo, which will be a git submodule.

**Comment by jackpot51** [comment]
That will include CJK examples, and right to left fonts.

**Pull request merged**
