### PR TITLE
Prevent GlyphNotCached due to ordering issues

### PR DESCRIPTION
**Pull request by michaelfairley**
The BTreeMap ordering in gpu_cache doesn't really work, since it's a one-dimensional ordering across a two-dimensional space. It's possible for adjacent glyphs in the map to not be considered "matches" (because their scale is the same but their position is not within the position tolerance), while matches further away in the map do match.

This PR changes `rect_for` and `cache_queued` to check every glyph already in `all_glyphs` for similarity, rather than only the ones adjacent to it in the BTreeMap. This comes with a very minor performance hit, but luckily helps simplify some code. I _think_ that this was the only place where the ordering aspect of the BTreeMap was actually being used, so you could likely convert to a HashMap to gain a tiny bit of performance back.

There's also an additional fix that prevents changes to the `oldest_in_use_row` from moving it forward in the LRU, since that could make it "more recent" than other currently-in-use rows.

I've also tested this branch against my game, where it's fixed a noticeable bug that causes various characters to occasionally not show up (due to `GlyphNotCached`).

(P.S. Huge thanks for the library! I'm shipping [my game](https://m12y.com/a-snakes-tale/) in the next few weeks, and rusttype has been _perfect_ for my font rendering needs.)

### CODE REVIEW

**Comment by dylanede** [comment]
Thanks for pinning down this issue. Others have reported similar behaviour. I'm not convinced the solution is ideal though. What it boils down to is that the similarity has to be checked in a four-dimensional space (x and y in scale and pixel offset). So probably a K-d tree would be best (I'm open to other ideas though). After I've looked through this in detail I might merge it, but only as a temporary solution.

Thanks for trusting RustType enough to use it in your game!

**Comment by alexheretic** [comment]
@dylanede @michaelfairley  I've been looking into this a little. To me it seems we have two primary concerns: Correct behaviour in regards to #52 & cache performance.

To try and help I've written a benchmark test that, at least on my machine / rusttype 0.2.1, reliably reproduces a GlyphNotCached error. With it we can try to address the issue without compromising performance.

rusttype version | position tolerance | benchmark
--- | --- | ---
0.2.1 master | 1.0 | 3,623,762 ns/iter (+/- 49,103)
0.2.1 master | 0.1 | *failed*
PR39-code | 1.0 | 8,378,997 ns/iter (+/- 176,811)
PR39-code | 0.1 | 123,299,414 ns/iter (+/- 804,216)

I'm going to have a play to see if I can improve on the performance of this PR for solving #52.

**Comment by jackpot51** [comment]
I am requesting transfer to another maintainer, please read and comment here: https://github.com/dylanede/rusttype/issues/55

**Comment by jackpot51** [comment]
Closed due to improvements in #53

**Pull request closed without merging**
