### PR TITLE
Add `rusttype::Error`, for `FontCollection` and `Font` operations.

### PR DESCRIPTION
**Pull request by jimblandy**
This is part of the work for issue #84, making rusttype handle errors in a more rustic fashion.

- Introduce `rusttype::Error`, which implements `std::error::Error`, `Debug` and `Display`, and can be converted to `std::io::Error`.
- Introduce `rusttype::Result`.
- Use `Result` to report failure in `FontCollection`, `Font`, and associated iterators.

### CODE REVIEW

**Comment by alexheretic** [comment]
This looks great thanks! I added your info to the changelog, _as I was making a tiny clippy fix_.

The only thing I'd question is why it's good to have `rusttype::Result<_>`, and not just use `Result<_, rusttype::Error>`? I always found even the io one a little strange and tended to import it as `IoResult`.

If its just to reduce syntax noise, in this case I think `Result<Font<'a>, Error>` looks fine.

**Comment by alexheretic** [comment]
@jackpot51 @jimblandy Let me modify the Result for now and so we can merge. We can re-add Result later if we decide it is better in the end, and I'm wrong _(wouldn't be a first)_.

**Comment by alexheretic** [comment]
Following on nicely from this I also want to add a convenience `Font::from_bytes` method. Will raise a PR.

**Comment by jimblandy** [comment]
> Let me modify the Result for now and so we can merge.

That's fine with me. Since it's a type alias, we could add it later without breaking anything.

> The only thing I'd question is why it's good to have rusttype::Result<_>, and not just use Result<_, rusttype::Error>?

Mostly just to match users' expectations. Since there are so many in the standard library, I think it's a pattern people are familiar with. But I don't have strong feelings about it.

**Comment by lo48576** [comment]
> The only thing I'd question is why it's good to have rusttype::Result<_>, and not just use Result<_, rusttype::Error>?

FYI: [TRPL (1st edition)](https://doc.rust-lang.org/book/first-edition/error-handling.html#the-result-type-alias-idiom) and [Rust By Example](https://rustbyexample.com/error/result/result_alias.html) describes about that idiom.

**Comment by alexheretic** [comment]
> FYI: TRPL (1st edition) and Rust By Example describes about that idiom.

Of course `std::io::Result` is familiar. But should this style be adopted everywhere? My feeling is it makes most sense when `Result` is used, and chained, a lot.

On the other hand, my feelings aren't particularly strong either, so I wouldn't mind having it if someone thought it improved their usage.

**Pull request merged**
